# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07e00e00c6ae55995dc06a61d35ef4933e2b3e928da1b5b8df915a2d7fd0e08777bddf498eddf6a209441f3a306199cd4c25d6bc03b09f5a5106f832944675f6

test:
  secret_key_base: 4f354f4d68aacdcc825d9f0aa01b0ecd53ab655274da11f8be23ae8ee7866362532200dd346fd06a90974672a0c1e79b75223bcfc04dc8b7b74a5f473c6fc76d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
